# Generated by Django 5.1.2 on 2024-11-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
