# Generated by Django 5.1.2 on 2024-11-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_pelanggan_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepeda',
            name='biaya_sepeda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sepeda',
            name='jenis_sepeda',
            field=models.CharField(choices=[('SG', 'Sepeda Gunung'), ('SE', 'SepedaElektrik'), ('SA', 'Sepeda Anak'), ('S', 'Skuter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sepeda',
            name='kondisi_sepeda',
            field=models.CharField(choices=[('R', 'Rusak'), ('B', 'Baik')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sepeda',
            name='status_sepeda',
            field=models.CharField(choices=[('T', 'Tersedia'), ('TT', 'Tidak Tersedia'), ('D', 'Dipinjam')], max_length=20),
        ),
    ]
