# Generated by Django 5.1.2 on 2024-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_sepeda_biaya_sepeda_alter_sepeda_jenis_sepeda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stasiun',
            name='jumlah_sepeda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sepeda',
            name='jenis_sepeda',
            field=models.CharField(choices=[('SG', 'Sepeda Gunung'), ('SE', 'Sepeda Elektrik'), ('SA', 'Sepeda Anak'), ('S', 'Skuter')], max_length=50),
        ),
    ]
