# Generated by Django 5.1.2 on 2024-11-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_stasiun_jumlah_sepeda_alter_sepeda_jenis_sepeda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stasiun',
            name='jumlah_sepeda',
        ),
    ]
