# Generated by Django 5.1.2 on 2024-11-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_remove_stasiun_jumlah_sepeda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepeda',
            name='biaya_sepeda',
        ),
    ]
